-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 11:39:18 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `employee_database` DEFAULT CHARACTER SET utf8 ;
USE `employee_database` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employee_database`.`employee` (
                                                 `employee_id` VARCHAR(255) NOT NULL,
    `user_id` VARCHAR(255) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `last_name` VARCHAR(255) NOT NULL,
    `address` VARCHAR(455) NOT NULL,
    `mobile_phone` VARCHAR(255) NOT NULL,
    `social_security_number` VARCHAR(255) NOT NULL,
    `id_number` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`employee_id`))
    ENGINE = InnoDB;

GRANT ALL PRIVILEGES ON customer_database.* TO 'admin'@'%';

GRANT ALL ON `employee_database`.* TO 'admin'@'%';

CREATE USER 'reader' IDENTIFIED BY 'reader-gespyme-2024-99Qabcde';

GRANT SELECT ON TABLE `employee_database`.* TO 'reader'@'%';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
