FROM mysql:oracle

COPY payment/01-payment-DDL.sql /docker-entrypoint-initdb.d/
COPY payment/02-init-data.sql /docker-entrypoint-initdb.d/

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_PAYMENT_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

EXPOSE 3306